title: Joseph's Resume
basseurl: "/online-cv/"
website: 'josephjctang.com'

# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
pic: avatar.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below



